### ISSUE TITLE
Calculate the number of events in the Z mass range [71,111] for the new 53X MC sample

### ISSUE THREAD

**Issue by duartej** [duartej/AnalysisVH#40]
See the twiki page how to do it

**Comment by duartej** [comment]
We don't have the sample in IFCA. I need to ask for or send a crab job...

**Comment by piedraj** [comment]
I have computed this number following the instructions in the TWiki page. The total number of generated WZ is 2017979. The number in the mass window (71 < mZ < 111) GeV is 1449067.

What I did (when the sample was still available at Oviedo) is:

  TChain\* evt = new TChain("Events");

  gSystem.Load("libFWCoreFWLite.so");

  AutoLibraryLoader::enable();

  evt->Add("/hadoop/phedexExtension/oviedo/cms/store/mc/Summer12_DR53X/WZJetsTo3LNu_TuneZ2_8TeV-madgraph-tauola/AODSIM/PU_S10_START53_V7A-v1/0000/*.root");

  gROOT->SetBatch();

  evt->Draw("genParticles.mass()","genParticles.pdgId() == 23 && genParticles.status() == 3 && genParticles.mass() > 71. && genParticles.mass() < 111.");

**Comment by duartej** [comment]
Great! So, as the number of events passed the Javi's skim are 1298553, but we don't know exactly how many events are inside the mass range we want), so we assume no bias in the skimming, then we can estimate the number of initial 71 < m_{ll}(Z) < 111. events in the 1298553 skimmed events as,
- 1298553*0.718078=932462

where  1449067/2017979=0.718078
The commit 4921f23bff8d2fa51ed7841b5c8e5af1fc4adaaa includes this change

**Comment by duartej** [comment]
Reopened due to a bug: last comment is wrong. The number of events generated for Z in [71,111] is 1449067. This number has to be used directly to extract the efficiency, which have been changed accordingly in the commit 5dd99207bd6d365a69825d88598d49082f617c1c
