### ISSUE TITLE
New 53X samples reprocessing: FR, SF and PR to be incorporated

### ISSUE THREAD

**Issue by duartej** [duartej/AnalysisVH#42]
See closed issue #36 to extract more info (issue related with the old 42X processing but also for 2012)

**Comment by duartej** [comment]
See commit f6dcfe5fb0cac11aafd3ce203695f91e308764d5 where the FR and SF for both muon and electrons are included for the 53X processing but with 12fb-1 (not yet the full 2012's luminosity: A+B+C?? Could you confirm that, Jónatan?)
Still missing the PR.

**Comment by piedraj** [comment]
They correspond to A+B+C. They will be replaced soon by the SF, FR and PR that correspond to the full 8 TeV luminosity. In other words, A+B+C+D.

**Comment by duartej** [comment]
Okey, don't forget to update this issue and close it when it finish

**Comment by duartej** [comment]
Any news about the SF, FR, PR and also the TR_leading and TR_trailing efficiencies?
