### ISSUE TITLE
Bugs found in HWWID selection

### ISSUE THREAD

**Issue by duartej** [duartej/AnalysisVH#49]
piedraj REPORTED,
- In line 439 in MuonSelection.cc,
  `_data->Get<int>("T_Muon_isPFMuon",i)` should be `_data->Get<int>("T_Muon_isPFMuon",i)`
  since the  _T_Muon_isPFMuon_ branch is a boolean. 
- In line 440 in MuonSelection.cc,
  `_data->Get<int>("T_Muon_NLayers")` should be  `_data->Get<int>("T_Muon_NLayers",i)`
  since the T_Muon_NLayers is a std::vector<int>, otherwise always it is used the first element.

**Comment by piedraj** [comment]
I have fixed them at

https://github.com/piedraj/AnalysisVH

Should I do Pull Request?

**Comment by duartej** [comment]
Thank you, J. 
Yes,  do the request and I will merge it

**Comment by piedraj** [comment]
Request done and merged.
