### ISSUE TITLE
WZ weight

### ISSUE THREAD

**Issue by piedraj** [duartej/AnalysisVH#58]
All MC samples take the number of generated events and expected cross section from the values gathered by the DatasetManager application. That is not correct for the WZ signal. In the case of the WZ signal, I believe that the weight should be:

   weight = (xsWplusZ + xsWminusZ) \* WZ23lnu \* luminosity / ngenWZphase

The input values for 8 TeV are:

const Double_t xsWplusZ      = 13.89;  // pb (MCFM with 71 < mZ < 111 GeV)
const Double_t xsWminusZ     =  8.06;  // pb (MCFM with 71 < mZ < 111 GeV)
const Double_t W2e         = 0.1075;
const Double_t W2m         = 0.1057;
const Double_t W2tau       = 0.1125;
const Double_t Z2ll        = 0.033658;
const Double_t WZ23lnu     = 3 \* Z2ll \* (W2e + W2m + W2tau);
const Double_t _luminosity = 12103.3;  // pb
const Double_t ngenWZphase = 1449067;  // (71 < mZ < 111 GeV)

The weight that we obtain with these values is 0.006029. The weight that we are currently using is 0.006343, about 5% larger. The modification of this weight would change the values of the data-driven estimation and the cross section.

**Comment by duartej** [comment]
Let me check that, I'll come back as soon as I can

**Comment by piedraj** [comment]
This issue is obsolete, now that we don't cut in the Z mass window for the WZ signal. See #59.
